# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LuMm5LRCbBLE_IPPqSRmUUQ1v1UDTOMC
"""

from flask import Flask

app = Flask(__name__)
add bad code

@app.route("/")
def hello():
    return "Hello World!"
