# -*- coding: utf-8 -*-
"""tests.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ern6L-Obbaed1Aj8PNzSBIvdGFfVhjFX
"""

from hello import app
with app.test_client() as c:
    response = c.get('/')
    assert response.data == b'Hello World!'
    assert response.status_code == 200